### ISSUE TITLE
ILI9341 display with touch and  Tasmota32-lvgl.bin not working

### ISSUE THREAD

**Issue by roesl** [Beormund/Tasmota32-Multi-Zone-Heating-Controller#10]
Hello, 

I installed tasmota32-lvgl and connectet the SPI display - but nothing happens - the display remains dark and with activated display in heating configuration no "Display" button appears - 

whats wrong ?

**Comment by Beormund** [comment]
Make sure you have the display set up using the Tasmota Universal Display driver:

https://tasmota.github.io/docs/Displays/#universal-display-driver.

In particular a free GPIO pin should be set to A3.

**Comment by roesl** [comment]
Which IOs  I have to set or use  for SPI display ?

 

Von: Beormund ***@***.***> 
Gesendet: Freitag, 30. Dezember 2022 18:09
An: Beormund/Tasmota32-Multi-Zone-Heating-Controller ***@***.***>
Cc: roesl ***@***.***>; Author ***@***.***>
Betreff: Re: [Beormund/Tasmota32-Multi-Zone-Heating-Controller] ILI9341 display with touch and Tasmota32-lvgl.bin not working (Issue #10)

 

Make sure you have the display set up using the Tasmota Universal Display driver:

https://tasmota.github.io/docs/Displays/#universal-display-driver.

In particular a free GPIO pin should be set to A3.

**Comment by Beormund** [comment]
That will depend on your particular display. You will need to check the documentation for your display.

**Comment by roesl** [comment]
I have the 4 wire SPI – which IOs are necessary and which IO s have to connect tot he ESP32

 

Von: Beormund ***@***.***> 
Gesendet: Freitag, 30. Dezember 2022 18:31
An: Beormund/Tasmota32-Multi-Zone-Heating-Controller ***@***.***>
Cc: roesl ***@***.***>; Author ***@***.***>
Betreff: Re: [Beormund/Tasmota32-Multi-Zone-Heating-Controller] ILI9341 display with touch and Tasmota32-lvgl.bin not working (Issue #10)

 

That will depend on your particular display. You will need to check the documentation for your display.

**Comment by Beormund** [comment]
https://tasmota.github.io/docs/Displays/#hardware-connections

**Comment by Beormund** [comment]
If you need further Tasmota support can I suggest you join the Discord Tasmota channel? Thanks.
